sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
before_install:
  - npm i -g npm@^2.0.0
  - npm i graphql graphql-compose
before_script:
  - npm prune
script:
  - npm run coverage
  - npm run build
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - bash <(curl -s https://codecov.io/bash)
  - npm run semantic-release
branches:
  only:
    - master
